version: '3.8'

services:
  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    environment:
      - NODE_ENV=development
      - VITE_APP_PORT=3010
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: [CMD, wget, --spider, 'http://localhost:3010']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    name: frontend-network
    driver: bridge
