version: '3.8'

services:
  frontend:
    image: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    volumes:
      - .:/app
    command: npm run dev
