name: Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug changed files
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Run labeler
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true

  labels:
    documentation:
      - 'docs/**'
      - '*.md'
    bug:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
    enhancement:
      - 'src/**'
    dependencies:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'package-lock.json'
    tests:
      - 'tests/**'
      - 'src/**/*.test.ts'
      - 'src/**/*.test.tsx'
    config:
      - '*.yml'
      - '*.yaml'
      - '.github/**'
    ci:
      - '.github/workflows/**'
    styles:
      - 'src/**/*.css'
      - 'src/**/*.scss'
      - 'src/**/*.sass'
    refactor:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
```
