name: Snyk Security

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Node.js for frontend dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk Code (SAST) analysis
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif || true

      # Run Snyk Open Source (SCA) analysis for frontend dependencies
      - name: Snyk Open Source monitor
        run: snyk monitor

      # Upload results to GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
